//go:build swagger

package httpapi

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	httpSwagger "github.com/swaggo/http-swagger"
	// docs is generated by swag when you run `swag init` (output default: ./docs)
	_ "modeld/docs"
)

// MountSwagger registers Swagger UI and the OpenAPI JSON routes when built with -tags=swagger.
// It mounts:
//   - /swagger/index.html (UI)
//   - /swagger/doc.json (spec)
func MountSwagger(r chi.Router) {
	// Serve the swagger UI via handler that reads embedded docs from docs package
	r.Get("/swagger/*", func(w http.ResponseWriter, req *http.Request) {
		httpSwagger.Handler(
			httpSwagger.URL("/swagger/doc.json"),
		).ServeHTTP(w, req)
	})
}
