models:
  - id: llama31-8b-q4km
    name: "Llama 3.1 8B Q4_K_M"
    path: "/models/llm/llama-3.1-8b-q4_k_m.gguf"
    quant: "Q4_K_M"
    family: "llama-3.1"
  - id: qwen2-7b-q5km
    name: "Qwen2 7B Q5_K_M"
    path: "/models/llm/qwen2-7b-q5_k_m.gguf"
    quant: "Q5_K_M"
    family: "qwen2"
