name: CI (E2E Cypress UI)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'web/**'
      - 'e2e/**'
      - 'scripts/**'
      - 'cmd/testctl/**'
      - 'internal/testctl/**'
      - '.github/workflows/ci-e2e-cypress.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'web/**'
      - 'e2e/**'
      - 'scripts/**'
      - 'cmd/testctl/**'
      - 'internal/testctl/**'
      - '.github/workflows/ci-e2e-cypress.yml'

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-cypress:
    name: E2E (Cypress UI)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Cache Go modules and build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Avoid using pnpm cache here because pnpm may not be installed yet in local act images

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        # Let action read the version from package.json's packageManager field

      - name: Install headless display (xvfb)
        run: |
          if command -v sudo >/dev/null 2>&1; then
            sudo apt-get update -y && sudo apt-get install -y xvfb
          else
            apt-get update -y && apt-get install -y xvfb
          fi

      - name: Install Cypress system dependencies (Ubuntu)
        run: |
          set -euo pipefail
          PKGS="\
          libnss3 \
          libatk-bridge2.0-0 \
          libgtk-3-0 \
          libgbm1 \
          libasound2t64 \
          libasound2 \
          libxss1 \
          libxtst6 \
          libnotify-dev \
          xauth \
          fonts-liberation \
          libdrm2 \
          "
          if command -v sudo >/dev/null 2>&1; then
            sudo apt-get update -y && sudo apt-get install -y $PKGS
          else
            apt-get update -y && apt-get install -y $PKGS
          fi

      - name: Download testctl artifact (if available)
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: testctl-bin-ubuntu
          path: bin

      - name: Ensure testctl exists (build if missing)
        run: |
          set -euo pipefail
          if [ ! -f bin/testctl ]; then
            echo "Artifact not found; building testctl from source"
            mkdir -p bin
            go build -o bin/testctl ./cmd/testctl
          else
            echo "Using downloaded testctl artifact"
            chmod +x bin/testctl
          fi

      - name: Install JS dependencies (via testctl)
        run: bin/testctl install js

      - name: Run Cypress (mock mode) via testctl
        env:
          WEB_PORT: 5173
        run: bin/testctl test web mock

      - name: Upload Cypress videos and screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            e2e/artifacts/screenshots
            e2e/artifacts/videos
