name: CI (E2E Python)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'tests/e2e_py/**'
      - '**/*.go'
      - 'cmd/modeld/**'
      - 'internal/**'
      - 'pkg/**'
      - '.github/workflows/ci-e2e-python.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'tests/e2e_py/**'
      - '**/*.go'
      - 'cmd/modeld/**'
      - 'internal/**'
      - 'pkg/**'
      - '.github/workflows/ci-e2e-python.yml'

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-python:
    name: E2E (Python)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Download Go dependencies
        run: go mod download

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('tests/e2e_py/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/e2e_py/requirements.txt

      - name: Run Python E2E tests
        run: |
          set -o pipefail
          pytest -q tests/e2e_py --junitxml=pytest-report.xml 2>&1 | tee pytest-output.txt

      - name: Upload pytest artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-artifacts-${{ matrix.python-version }}
          path: |
            pytest-report.xml
            pytest-output.txt
