name: CI (Deprecated)

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  note:
    name: Deprecated CI workflow
    runs-on: ubuntu-latest
    steps:
      - name: Print deprecation notice
        run: |
          echo "This workflow is deprecated. Use the split workflows instead:"
          echo " - .github/workflows/ci-go.yml"
          echo " - .github/workflows/ci-e2e-python.yml"
          echo " - .github/workflows/ci-e2e-cypress.yml"
          echo " - .github/workflows/ci-e2e-cypress-live.yml (manual)"
